# Generated by Django 2.0.5 on 2019-03-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_userprofile',
        ),
    ]
